services:
  api:
    build:
      context: ./api
    ports:
      - "8000:8000"
    environment:
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${POSTGRES_DB}
    depends_on:
      - db
    networks:
      - monitoring

  nginx:
    build:
      context: ./nginx
    ports:
      - "8080:80"
    depends_on:
      - api
    volumes:
      - ./api/site:/usr/share/nginx/html:ro
    networks:
      - monitoring

  db:
    image: postgres:18
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      TZ: ${TZ}
      POSTGRES_INITDB_ARGS: ${POSTGRES_INITDB_ARGS}
    volumes:
      - ./db/init/my-postgres.conf:/etc/postgresql/postgresql.conf:ro
      - ./db/init/init-db:/docker-entrypoint-initdb.d:ro
      - postgres_data:/var/lib/postgresql
    command: postgres -c config_file=/etc/postgresql/postgresql.conf
    networks:
      - monitoring

volumes:
  postgres_data:

networks:
  monitoring:
    name: monitoring_network
