FROM kalilinux/kali-rolling

RUN apt-get update && \
    apt-get install -y \
        curl \
        nmap \
        netcat-openbsd \
        dnsutils \
        iproute2 \
        iputils-ping \
        wget \
        net-tools && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists[]

CMD ["/bin/bash"]