# Wazuh App Copyright (C) 2017, Wazuh Inc. (License GPLv2)
services:
  wazuh.agent:
    image: wazuh/wazuh-agent:4.14.3
    restart: always
    environment:
      - WAZUH_MANAGER_SERVER: wazuh-manager
    volumes:
      - ./config/wazuh-agent-conf:/wazuh-config-mount/etc/ossec.conf
      # Pour surveiller les événements Docker
      - /var/run/docker.sock:/var/run/docker.sock:ro
      # Pour surveiller les logs et fichiers de l'hôte
      - /var/log:/host/var/log:ro
      - /etc:/host/etc:ro

    networks:
      - monitoring

networks:
  monitoring:
    external: true
    name: monitoring_network